In [1]:
import cv2
import math
import matplotlib.pyplot as plt
import numpy as np
import sys
import time

In [2]:
ball_cam1=np.array([583,299])
ball_cam2=np.array([760,277])

In [18]:
cam1_R=np.array([[0.9549,-0.2120,0.2078],
                  [0.2953,0.7503,-0.5914],
                  [-0.0305,0.6261,0.7791]])

cam2_R=np.array([[0.7009,-0.3537,0.6194],
                  [0.7128,0.3172,-0.6255],
                  [0.0248,0.8799,0.4744]])

cam1_T=np.array([-1141.732,135.2270,1683.209])

cam2_T=np.array([-394.3632,163.9281,1394.106])

#Translation Matrix between each cam & World Coord

cam1_Trans=np.zeros((4,4))
cam2_Trans=np.zeros((4,4))

cam1_Trans[0:3,0:3]=cam1_R
cam1_Trans[0:3,3]=cam1_T
cam1_Trans[3,:]=[0,0,0,1]

cam2_Trans[0:3,0:3]=cam2_R
cam2_Trans[0:3,3]=cam2_T
cam2_Trans[3,:]=[0,0,0,1]

cam1_oc=np.dot(cam1_R,cam1_T)
cam2_oc=np.dot(cam2_R,cam2_T)

cam1_R_inv=np.linalg.inv(cam1_R)
cam2_R_inv=np.linalg.inv(cam2_R)

#Cam Coordinate
print('Rotaion Matrix')
print('-cam-->>world-')
print('')
print(cam1_R)
print('')
print(cam2_R)
print('')
print('')
print('World Coordinate about Cam')
print('------cam--->>>world------')
print('')
print(cam1_T)
print('')
print(cam2_T)
print('')
print('')
print('Trans M between cam & world')
print('')
print(cam1_Trans)
print('')
print(cam2_Trans)
print('')
print('')
print('Inversed Rotation Matrix')
print('-----world--->>>cam-----')
print('')
print(cam1_R_inv)
print('')
print(cam2_R_inv)
print('')
print('')
print('Cam Coordinate about World')
print('------world--->>>cam------')
print('')
print(cam1_oc)
print('')
print(cam2_oc)

Rotaion Matrix
-cam-->>world-

[[-0.9549  0.212  -0.2078]
 [-0.2953 -0.7503  0.5914]
 [ 0.0305 -0.6261 -0.7791]]

[[-0.7009  0.3537 -0.6194]
 [-0.7128 -0.3172  0.6255]
 [-0.0248 -0.8799 -0.4744]]


World Coordinate about Cam
------cam--->>>world------

[-1141.732   135.227  1683.209]

[-394.3632  163.9281 1394.106 ]


Trans M between cam & world

[[-9.549000e-01  2.120000e-01 -2.078000e-01 -1.141732e+03]
 [-2.953000e-01 -7.503000e-01  5.914000e-01  1.352270e+02]
 [ 3.050000e-02 -6.261000e-01 -7.791000e-01  1.683209e+03]
 [ 0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00]]

[[-7.009000e-01  3.537000e-01 -6.194000e-01 -3.943632e+02]
 [-7.128000e-01 -3.172000e-01  6.255000e-01  1.639281e+02]
 [-2.480000e-02 -8.799000e-01 -4.744000e-01  1.394106e+03]
 [ 0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00]]


Inversed Rotation Matrix
-----world--->>>cam-----

[[-0.95493298 -0.29530331  0.0305387 ]
 [ 0.21205245 -0.75037806 -0.62615593]
 [-0.20779296  0.59145803 -0.77914561]]

[[-0

In [40]:
cam1_R=np.array([[0.9549,-0.2120,0.2078],
                  [0.2953,0.7503,-0.5914],
                  [-0.0305,0.6261,0.7791]])

x_axis=np.array([1,0,0])
y_axis=np.array([0,1,0])
z_axis=np.array([0,0,1])


x_t=np.dot(cam1_R,x_axis)
y_t=np.dot(cam1_R,y_axis)
z_t=np.dot(cam1_R,z_axis)

print(x_t)
print(y_t)
print(z_t)

[ 0.9549  0.2953 -0.0305]
[-0.212   0.7503  0.6261]
[ 0.2078 -0.5914  0.7791]


In [19]:
# cam1_Trans=np.array([[cam1_R[0,0],cam1_R[0,1],cam1_R[0,2],cam1_T[0]],
#                    [cam1_R[1,0],cam1_R[1,1],cam1_R[1,2],cam1_T[1]],
#                    [cam1_R[2,0],cam1_R[2,1],cam1_R[2,2],cam1_T[2]],
#                     [0,0,0,1]])
                    
# cam2_Trans=np.array([[cam2_R[0,0],cam2_R[0,1],cam2_R[0,2],cam2_T[0]],
#                    [cam2_R[1,0],cam2_R[1,1],cam2_R[1,2],cam2_T[1]],
#                    [cam2_R[2,0],cam2_R[2,1],cam2_R[2,2],cam2_T[2]],
#                     [0,0,0,1]])

I_matrix=np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0]])


cam1_T_h=np.zeros((4,1))
cam1_T_h[0:3,0]=cam1_T
cam1_T_h[3,0]=1

cam2_T_h=np.zeros((4))
cam2_T_h[0:3]=cam2_T
cam2_T_h[3]=1

#homogeneous oc
cam1_oc_h=np.zeros(4)
cam1_oc_h[0:3]=cam1_oc
cam1_oc_h[3]=1

print(cam1_oc_h)

cam2_oc_h=np.zeros(4)
cam2_oc_h[0:3]=cam2_oc
cam2_oc_h[3]=1

print(cam2_oc_h)

# transformation matrix for world->cam

cam1_Trans_t=np.zeros((4,4))
cam2_Trans_t=np.zeros((4,4))

cam1_Trans_t[0:3,0:3]=cam1_R_inv
cam1_Trans_t[0:4,3]=cam1_oc_h

cam2_Trans_t[0:3,0:3]=cam2_R_inv
cam2_Trans_t[0:4,3]=cam2_oc_h

cam_Fun_M=np.dot(np.linalg.inv(cam1_Trans),cam2_Trans)

# cam_Fun_T=np.dot(cam_Fun_R,cam2_T)
# cam_Fun_M=np.zeros((4,4))
# cam_Fun_M[0:3,0:3]=cam_Fun_R
# cam_Fun_M[0:3,3]=cam_Fun_T

# result=np.dot(cam_Fun_M,cam2_T_h)

print('')
print('')
print('Transposed Transformation Matrix')
print('')
print(cam1_Trans_t)
print('')
print(cam2_Trans_t)
print('')
print('')

# print('World Coordinate about Cam')
# print('------cam--->>>world------')
# print('')
# print(cam1_T)
# print('')
# print(cam2_T)
# print('')
# print('')
# print('Cam Coordinate about World')
# print('------world--->>>cam------')
# print('')
# print(cam1_oc)
# print('')
# print(cam2_oc)
# print('')
# print('')

print('I-Matrix')
print('')
print(I_matrix)
print('')
print('')


print('Fundamental Matrix')

# print('')
# print(cam_Fun_R)
# print('')
# print(cam_Fun_T)

print('')
# print(cam2_T_h)
print('')
print(cam_Fun_M)
print('')

# print(result)

[ 7.69137181e+02  1.23114244e+03 -1.43087658e+03  1.00000000e+00]
[-5.29118721e+02  1.10111740e+03 -7.95824014e+02  1.00000000e+00]


Transposed Transformation Matrix

[[-9.54932981e-01 -2.95303305e-01  3.05386968e-02  7.69137181e+02]
 [ 2.12052450e-01 -7.50378056e-01 -6.26155926e-01  1.23114244e+03]
 [-2.07792959e-01  5.91458029e-01 -7.79145610e-01 -1.43087658e+03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]

[[-7.00904373e-01 -7.12853388e-01 -2.47673394e-02 -5.29118721e+02]
 [ 3.53688560e-01 -3.17167218e-01 -8.79980583e-01  1.10111740e+03]
 [-6.19367907e-01  6.25535833e-01 -4.74474821e-01 -7.95824014e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


I-Matrix

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


Fundamental Matrix


[[ 8.79047363e-01 -2.70960586e-01  3.92285713e-01 -7.30991475e+02]
 [ 4.01770583e-01  8.63977470e-01 -3.03658391e-01  3.17968266e+02]
 [-2.56626387e-01  4.24463366e-01  8.68290634e-01  8.69308545e+01]
 [ 0.00000000e+00  0.00

In [34]:
#Focallength(Re)
cam1_f=np.array([763.2494,764.9436])
cam2_f=np.array([940.6457,942.8740])

#Principle Point(Re)
cam1_c=np.array([648.2271,345.6770])
cam2_c=np.array([639.3781,369.1142])

#Distortion
cam1_dist_r=np.array([0.2033,-0.4879,0.2806])
cam1_dist_t=np.array([0,0])
cam2_dist_r=np.array([0.2134,-0.5762,0.4176])
cam2_dist_t=np.array([0,0])

#Intrinsics Matrix
cam1_int=np.array([[cam1_f[0],0,cam1_c[0]],[0,cam1_f[1],cam1_c[1]],[0,0,1]])
cam2_int=np.array([[cam2_f[0],0,cam2_c[0]],[0,cam2_f[1],cam2_c[1]],[0,0,1]])

print('intrinsics Matrix')
print('')
print(cam1_int)
print(cam2_int)

intrinsics Matrix

[[763.2494   0.       0.    ]
 [  0.       0.     345.677 ]
 [648.2271 764.9436   1.    ]]
[[940.6457   0.       0.    ]
 [  0.       0.     369.1142]
 [639.3781 942.874    1.    ]]


In [35]:
#Projection Matrix about World Coordinate

cam1_Proj=np.dot(cam1_int,I_matrix)
cam1_Proj=np.dot(cam1_Proj,cam1_Trans_t)
cam2_Proj=np.dot(cam2_int,I_matrix)
cam2_Proj=np.dot(cam2_Proj,cam2_Trans_t)

# cam1_Proj=np.dot(cam1_int,I_matrix)
# cam1_Proj=np.dot(cam1_Proj,np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]]))
                                     
# cam2_Proj=np.dot(cam2_int,I_matrix)
# cam2_Proj=np.dot(cam2_Proj,cam_Fun_M)
                                     
print('Projective Matrix')
print('')
print(cam1_Proj)
print(cam2_Proj)

Projective Matrix

[[-7.28852025e+02 -2.25390071e+02  2.33086420e+01  5.87043492e+05]
 [-7.18292469e+01  2.04453437e+02 -2.69332717e+02 -4.94621124e+05]
 [-4.57013066e+02 -7.64829039e+02 -4.59957103e+02  1.43889922e+06]]
[[-6.59302684e+02 -6.70542474e+02 -2.32972913e+01 -4.97713249e+05]
 [-2.28617490e+02  2.30894158e+02 -1.75135394e+02 -2.93749944e+05]
 [-1.15278527e+02 -7.54206032e+02 -8.46020981e+02  6.99112220e+05]]


In [36]:
ball_3D=np.array(cv2.triangulatePoints(cam1_Proj,cam2_Proj,ball_cam1,ball_cam2))
# ball_3D=np.array([ball_3D[0]/ball_3D[3],ball_3D[1]/ball_3D[3],ball_3D[2]/ball_3D[3],ball_3D[3]/ball_3D[3]]])


print('ball_cam1')
print(ball_cam1)
print('ball_cam2')
print(ball_cam2)
print('ball_3D')
print(ball_3D[0]/ball_3D[3])
print(ball_3D[1]/ball_3D[3])
print(ball_3D[2]/ball_3D[3])


ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[0.70974864]
[7.32421326]
[-4.45957697]
