In [34]:
import cv2
import numpy as np
import sys
import time

# Set Initial Value

In [46]:
ball_cam1=np.array([0,0])
ball_cam2=np.array([0,0])
ball_3D_temp=np.array([[0],[0],[0],[1]])

# Set Camera Matrix

In [36]:
cam1_R=-np.array([[0.9549,-0.2120,0.2078],
                  [0.2953,0.7503,-0.5914],
                  [-0.0305,0.6261,0.7791]])

cam2_R=-np.array([[0.7009,-0.3537,0.6194],
                  [0.7128,0.3172,-0.6255],
                  [0.0248,0.8799,0.4744]])

cam1_T=np.array([-1141.732,135.2270,1683.209])

cam2_T=np.array([-394.3632,163.9281,1394.106])

#Translation Matrix between each cam & World Coord

cam1_Trans=np.zeros((4,4))
cam2_Trans=np.zeros((4,4))

cam1_Trans[0:3,0:3]=cam1_R
cam1_Trans[0:3,3]=cam1_T
cam1_Trans[3,:]=[0,0,0,1]

cam2_Trans[0:3,0:3]=cam2_R
cam2_Trans[0:3,3]=cam2_T
cam2_Trans[3,:]=[0,0,0,1]

cam1_oc=np.dot(cam1_R,cam1_T)
cam2_oc=np.dot(cam2_R,cam2_T)

cam1_R_inv=-np.linalg.inv(cam1_R)
cam2_R_inv=-np.linalg.inv(cam2_R)

#Cam Coordinate
print('Rotaion Matrix')
print('-cam-->>world-')
print('')
print(cam1_R)
print('')
print(cam2_R)
print('')
print('')
print('World Coordinate about Cam')
print('------cam--->>>world------')
print('')
print(cam1_T)
print('')
print(cam2_T)
print('')
print('')
print('Trans M between cam & world')
print('')
print(cam1_Trans)
print('')
print(cam2_Trans)
print('')
print('')
print('Inversed Rotation Matrix')
print('-----world--->>>cam-----')
print('')
print(cam1_R_inv)
print('')
print(cam2_R_inv)
print('')
print('')
print('Cam Coordinate about World')
print('------world--->>>cam------')
print('')
print(cam1_oc)
print('')
print(cam2_oc)

Rotaion Matrix
-cam-->>world-

[[-0.9549  0.212  -0.2078]
 [-0.2953 -0.7503  0.5914]
 [ 0.0305 -0.6261 -0.7791]]

[[-0.7009  0.3537 -0.6194]
 [-0.7128 -0.3172  0.6255]
 [-0.0248 -0.8799 -0.4744]]


World Coordinate about Cam
------cam--->>>world------

[-1141.732   135.227  1683.209]

[-394.3632  163.9281 1394.106 ]


Trans M between cam & world

[[-9.549000e-01  2.120000e-01 -2.078000e-01 -1.141732e+03]
 [-2.953000e-01 -7.503000e-01  5.914000e-01  1.352270e+02]
 [ 3.050000e-02 -6.261000e-01 -7.791000e-01  1.683209e+03]
 [ 0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00]]

[[-7.009000e-01  3.537000e-01 -6.194000e-01 -3.943632e+02]
 [-7.128000e-01 -3.172000e-01  6.255000e-01  1.639281e+02]
 [-2.480000e-02 -8.799000e-01 -4.744000e-01  1.394106e+03]
 [ 0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00]]


Inversed Rotation Matrix
-----world--->>>cam-----

[[ 0.95493298  0.29530331 -0.0305387 ]
 [-0.21205245  0.75037806  0.62615593]
 [ 0.20779296 -0.59145803  0.77914561]]

[[ 0

In [37]:
# cam1_Trans=np.array([[cam1_R[0,0],cam1_R[0,1],cam1_R[0,2],cam1_T[0]],
#                    [cam1_R[1,0],cam1_R[1,1],cam1_R[1,2],cam1_T[1]],
#                    [cam1_R[2,0],cam1_R[2,1],cam1_R[2,2],cam1_T[2]],
#                     [0,0,0,1]])
                    
# cam2_Trans=np.array([[cam2_R[0,0],cam2_R[0,1],cam2_R[0,2],cam2_T[0]],
#                    [cam2_R[1,0],cam2_R[1,1],cam2_R[1,2],cam2_T[1]],
#                    [cam2_R[2,0],cam2_R[2,1],cam2_R[2,2],cam2_T[2]],
#                     [0,0,0,1]])

I_matrix=np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0]])
cam1_T_h=np.zeros((4,1))
cam1_T_h[0:3,0]=cam1_T
cam1_T_h[3,0]=1

cam2_T_h=np.zeros((4))
cam2_T_h[0:3]=cam2_T
cam2_T_h[3]=1

#homogeneous oc
cam1_oc_h=np.zeros(4)
cam1_oc_h[0:3]=cam1_oc
cam1_oc_h[3]=1
print(cam1_oc_h)

cam2_oc_h=np.zeros(4)
cam2_oc_h[0:3]=cam2_oc
cam2_oc_h[3]=1
print(cam2_oc_h)

# transformation matrix for world->cam

cam1_Trans_t=np.zeros((4,4))
cam2_Trans_t=np.zeros((4,4))

cam1_Trans_t[0:3,0:3]=np.linalg.inv(cam1_R)
cam1_Trans_t[0:4,3]=cam1_oc_h

cam2_Trans_t[0:3,0:3]=np.linalg.inv(cam2_R)
cam2_Trans_t[0:4,3]=cam2_oc_h

cam_Fun_M=np.dot(cam1_Trans,np.linalg.inv(cam2_Trans))

# cam_Fun_T=np.dot(cam_Fun_R,cam2_T)
# cam_Fun_M=np.zeros((4,4))
# cam_Fun_M[0:3,0:3]=cam_Fun_R
# cam_Fun_M[0:3,3]=cam_Fun_T

# result=np.dot(cam_Fun_M,cam2_T_h)
print('')
print('')
print('Transposed Transformation Matrix')
print('')
print(cam1_Trans_t)
print('')
print(cam2_Trans_t)
print('')
print('')

print('World Coordinate about Cam')
print('------cam--->>>world------')
print('')
print(cam1_T)
print('')
print(cam2_T)
print('')
print('')
print('Cam Coordinate about World')
print('------world--->>>cam------')
print('')
print(cam1_oc)
print('')
print(cam2_oc)
print('')
print('')

print('I-Matrix')
print('')
print(I_matrix)
print('')
print('')


print('Fundamental Matrix')

# print('')
# print(cam_Fun_R)
# print('')
# print(cam_Fun_T)

print('')
print(cam2_T_h)
print('')
print(cam_Fun_M)
print('')

# print(result)

[ 7.69137181e+02  1.23114244e+03 -1.43087658e+03  1.00000000e+00]
[-5.29118721e+02  1.10111740e+03 -7.95824014e+02  1.00000000e+00]


Transposed Transformation Matrix

[[-9.54932981e-01 -2.95303305e-01  3.05386968e-02  7.69137181e+02]
 [ 2.12052450e-01 -7.50378056e-01 -6.26155926e-01  1.23114244e+03]
 [-2.07792959e-01  5.91458029e-01 -7.79145610e-01 -1.43087658e+03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]

[[-7.00904373e-01 -7.12853388e-01 -2.47673394e-02 -5.29118721e+02]
 [ 3.53688560e-01 -3.17167218e-01 -8.79980583e-01  1.10111740e+03]
 [-6.19367907e-01  6.25535833e-01 -4.74474821e-01 -7.95824014e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


World Coordinate about Cam
------cam--->>>world------

[-1141.732   135.227  1683.209]

[-394.3632  163.9281 1394.106 ]


Cam Coordinate about World
------world--->>>cam------

[  769.1371806  1231.1424441 -1430.8765826]

[-529.11872055 1101.11739864 -795.82401423]


I-Matrix

[[1 0 0 0]
 [

# Intrinsics Params(Re)

In [38]:
#Focallength(Re)
cam1_f=np.array([763.2494,764.9436])
cam2_f=np.array([940.6457,942.8740])

#Principle Point(Re)
cam1_c=np.array([648.2271,345.6770])
cam2_c=np.array([639.3781,369.1142])

#Distortion
cam1_dist_r=np.array([0.2033,-0.4879,0.2806])
cam1_dist_t=np.array([0,0])
cam2_dist_r=np.array([0.2134,-0.5762,0.4176])
cam2_dist_t=np.array([0,0])

#Intrinsics Matrix
cam1_int=np.array([[cam1_f[0],0,cam1_c[0]],[0,cam1_f[1],cam1_c[1]],[0,0,1]])
cam2_int=np.array([[cam2_f[0],0,cam2_c[0]],[0,cam2_f[1],cam2_c[1]],[0,0,1]])

print('intrinsics Matrix')
print('')
print(cam1_int)
print(cam2_int)

intrinsics Matrix

[[763.2494   0.     648.2271]
 [  0.     764.9436 345.677 ]
 [  0.       0.       1.    ]]
[[940.6457   0.     639.3781]
 [  0.     942.874  369.1142]
 [  0.       0.       1.    ]]


In [39]:
# #Projection Matrix about World Coordinate

# cam1_Proj=np.dot(cam1_int,I_matrix)
# cam1_Proj=np.dot(cam1_Proj,cam1_Trans_t)
# cam2_Proj=np.dot(cam2_int,I_matrix)
# cam2_Proj=np.dot(cam2_Proj,cam2_Trans_t)

# print('Projective Matrix')
# print('')
# print(cam1_Proj)
# print(cam2_Proj)

In [41]:
cam1_Proj=np.dot(cam1_int,I_matrix)
cam1_Proj=np.dot(cam1_Proj,np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]]))
                                     
cam2_Proj=np.dot(cam2_int,I_matrix)
cam2_Proj=np.dot(cam2_Proj,cam_Fun_M)
                                     
print('Projective Matrix')
print('')
print(cam1_Proj)
print(cam2_Proj)

Projective Matrix

[[763.2494   0.     648.2271   0.    ]
 [  0.     764.9436 345.677    0.    ]
 [  0.       0.       1.       0.    ]]
[[ 9.74441625e+02  2.56242619e+02  5.27648124e+02 -3.91077187e+05]
 [-3.11941983e+02  6.57048286e+02  7.04388189e+02 -4.63920550e+05]
 [ 2.39727546e-01 -3.10518601e-01  9.19863772e-01  5.46263842e+02]]


In [42]:
# 트랙바 콜백 함수 생성
def nothing(x):
    
    pass

def on_trackbar_1():
    
    global hmin_1,hmax_1,smin_1,smax_1,vmin_1,vmax_1

    hmin_1 = cv2.getTrackbarPos('H_min_1', 'dst_1')
    hmax_1 = cv2.getTrackbarPos('H_max_1', 'dst_1')
    smin_1 = cv2.getTrackbarPos('S_min_1', 'dst_1')
    smax_1 = cv2.getTrackbarPos('S_max_1', 'dst_1')
    vmin_1 = cv2.getTrackbarPos('V_min_1', 'dst_1')
    vmax_1 = cv2.getTrackbarPos('V_max_1', 'dst_1')
    
def on_trackbar_2():
    
    global hmin_2,hmax_2,smin_2,smax_2,vmin_2,vmax_2
    
    hmin_2 = cv2.getTrackbarPos('H_min_2', 'dst_2')
    hmax_2 = cv2.getTrackbarPos('H_max_2', 'dst_2')
    smin_2 = cv2.getTrackbarPos('S_min_2', 'dst_2')
    smax_2 = cv2.getTrackbarPos('S_max_2', 'dst_2')
    vmin_2 = cv2.getTrackbarPos('V_min_2', 'dst_2')
    vmax_2 = cv2.getTrackbarPos('V_max_2', 'dst_2')

In [43]:
mask1=cv2.imread('cam1_mask.jpg',cv2.IMREAD_GRAYSCALE)
mask2=cv2.imread('cam2_mask.jpg',cv2.IMREAD_GRAYSCALE)

In [44]:
# cv2.namedWindow('src')

cv2.namedWindow('dst_1')
cv2.namedWindow('dst_2')

# Set Trackbar

cv2.createTrackbar('H_min_1', 'dst_1', 0, 255, nothing)
cv2.setTrackbarPos('H_min_1', 'dst_1',0)
cv2.createTrackbar('H_max_1', 'dst_1', 0, 255, nothing)
cv2.setTrackbarPos('H_max_1', 'dst_1',255)
cv2.createTrackbar('S_min_1', 'dst_1', 0, 255, nothing)
cv2.setTrackbarPos('S_min_1', 'dst_1',0)
cv2.createTrackbar('S_max_1', 'dst_1', 0, 255, nothing)
cv2.setTrackbarPos('S_max_1', 'dst_1',255)
cv2.createTrackbar('V_min_1', 'dst_1', 0, 255, nothing)
cv2.setTrackbarPos('V_min_1', 'dst_1',0)
cv2.createTrackbar('V_max_1', 'dst_1', 0, 255, nothing)
cv2.setTrackbarPos('V_max_1', 'dst_1',255)

cv2.createTrackbar('H_min_2', 'dst_2', 0, 255, nothing)
cv2.setTrackbarPos('H_min_2', 'dst_2',0)
cv2.createTrackbar('H_max_2', 'dst_2', 0, 255, nothing)
cv2.setTrackbarPos('H_max_2', 'dst_2',255)
cv2.createTrackbar('S_min_2', 'dst_2', 0, 255, nothing)
cv2.setTrackbarPos('S_min_2', 'dst_2',0)
cv2.createTrackbar('S_max_2', 'dst_2', 0, 255, nothing)
cv2.setTrackbarPos('S_max_2', 'dst_2',255)
cv2.createTrackbar('V_min_2', 'dst_2', 0, 255, nothing)
cv2.setTrackbarPos('V_min_2', 'dst_2',0)
cv2.createTrackbar('V_max_2', 'dst_2', 0, 255, nothing)
cv2.setTrackbarPos('V_max_2', 'dst_2',255)

In [45]:
while(True):
    
    src_1 = cv2.imread('3D_cam1_ex1.jpg')
    src_1 = cv2.copyTo(src_1,mask1)
    
    src_2 = cv2.imread('3D_cam2_ex1.jpg')
    src_2 = cv2.copyTo(src_2,mask2)
   

#     #이미지 불러와졌는지
#     if src is None:
#         print('Image load failed!')
#         sys.exit()
    
    cv2.imshow('src_1', src_1)
    cv2.imshow('src_2', src_2)
    
    src_hsv_1 = cv2.cvtColor(src_1, cv2.COLOR_BGR2HSV)
    src_hsv_2 = cv2.cvtColor(src_2, cv2.COLOR_BGR2HSV)
    
    #Trackbar 불러오기
    on_trackbar_1()
    on_trackbar_2()
    
    #Detecting Color Setting
    dst_1 = cv2.inRange(src_hsv_1, (hmin_1, smin_1, vmin_1), (hmax_1, smax_1, vmax_1))
    dst_2 = cv2.inRange(src_hsv_2, (hmin_2, smin_2, vmin_2), (hmax_2, smax_2, vmax_2))
    
    cv2.imshow('dst_1', dst_1)
    cv2.imshow('dst_2', dst_2)
    
    #MORPH 함수 이용하여 정확도 향상(Value Optimization)
    kernel = np.ones((11,11), np.uint8)
    dst_1 = cv2.morphologyEx(dst_1, cv2.MORPH_OPEN, kernel)
    dst_1 = cv2.morphologyEx(dst_1, cv2.MORPH_CLOSE, kernel)
    dst_2 = cv2.morphologyEx(dst_2, cv2.MORPH_OPEN, kernel)
    dst_2 = cv2.morphologyEx(dst_2, cv2.MORPH_CLOSE, kernel)
    
    # 마스크 이미지로 원본 이미지에서 범위값에 해당되는 영상 부분을 획득
    #실제 구동시 X
    img_result_1 = cv2.bitwise_and(src_1, src_1, mask=dst_1)
    img_result_2 = cv2.bitwise_and(src_2, src_2, mask=dst_2)
    
    
    numOfLabels_1, img_label_1, stats_1, centroids_1 = cv2.connectedComponentsWithStats(dst_1)
    numOfLabels_2, img_label_2, stats_2, centroids_2 = cv2.connectedComponentsWithStats(dst_2)
    
    #centroids==무게중심 좌표(x,y)
    
    for idx, centroid in enumerate(centroids_1):
        if stats_1[idx][0] == 0 and stats_1[idx][1] == 0:
            continue

        if np.any(np.isnan(centroid)):
            continue

        x,y,width,height,area = stats_1[idx]
        centerX,centerY = int(centroid[0]), int(centroid[1])
        #print(centerX, centerY)

        if area > 50 and area < 1000:
        
            # 일정 범위 이상 & 이하인 부분에 대해서만 centroids 값 반환
            
            cv2.circle(src_1, (centerX, centerY), 10, (0,0,255), 10)
            cv2.rectangle(src_1, (x,y), (x+width,y+height), (0,0,255))
            ball_cam1=np.array([int(centroid[0]),int(centroid[1])])
#             print(ball_cam1)
            
    for idx, centroid in enumerate(centroids_2):
        if stats_2[idx][0] == 0 and stats_2[idx][1] == 0:
            continue

        if np.any(np.isnan(centroid)):
            continue

        x,y,width,height,area = stats_2[idx]
        centerX,centerY = int(centroid[0]), int(centroid[1])
        #print(centerX, centerY)

        if area > 50 and area < 1000:
            # 일정 범위 이상 & 이하인 부분에 대해서만 centroids 값 반환
            cv2.circle(src_2, (centerX, centerY), 10, (0,0,255), 10)
            cv2.rectangle(src_2, (x,y), (x+width,y+height), (0,0,255))
            ball_cam2=np.array([int(centroid[0]),int(centroid[1])])
             #print(ball_cam2)
            
    if ball_cam1[0]!=0 and ball_cam2[0]!=0:
        ball_3D=np.array(cv2.triangulatePoints(cam1_Proj,cam2_Proj,ball_cam1,ball_cam2))
    else:
        ball_3D=ball_3D_temp
    
    
    
    
    
    #Display
    
    cv2.imshow('src_1', src_1)
    cv2.imshow('dst_1',dst_1)
    cv2.imshow('img_result_1', img_result_1)
    
    cv2.imshow('src_2',src_2)
    cv2.imshow('dst_2',dst_2)
    cv2.imshow('img_result_2', img_result_2)
    
    #Store temp value for Predicting
    
    ball_cam1_temp=ball_cam1
    ball_cam2_temp=ball_cam2
    
    ball_3D_temp=ball_3D
    print('ball_cam1')
    print(ball_cam1)
    print('ball_cam2')
    print(ball_cam2)
    print('ball_3D')
    print(ball_3D)
    
    if cv2.waitKey(1) & 0xFF == 27:
        break
    
    
cv2.destroyAllWindows()

ball_cam1
[0 0]
ball_cam2
[0 0]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[0 0]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[0 0]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[0 0]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[0 0]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[0 0]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[0 0]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[0 0]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[0 0]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[0 0]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[0 0]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[0 0]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[0 0]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[0 0]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[0 0]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[0 0]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[0 0]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[0 0]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[0 0]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[0 0]
ball_3D
[0 0 0 1]


ball_cam1
[0 0]
ball_cam2
[0 0]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[0 0]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[0 0]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[0 0]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[0 0]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[0 0]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[0 0]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[0 0]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[0 0]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[0 0]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[0 0]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[0 0]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[0 0]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[0 0]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[0 0]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[0 0]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[0 0]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[0 0]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[0 0]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[0 0]
ball_3D
[0 0 0 1]


ball_cam1
[0 0]
ball_cam2
[738 715]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[738 715]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[738 715]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[738 715]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[738 715]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[738 715]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[738 715]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[738 715]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[738 715]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[760 277]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[760 277]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[760 277]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[760 277]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[760 277]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[760 277]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[760 277]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[760 277]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[760 277]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[7

ball_cam1
[0 0]
ball_cam2
[760 277]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[760 277]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[760 277]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[760 277]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[760 277]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[760 277]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[760 277]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[760 277]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[760 277]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[760 277]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[760 277]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[760 277]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[760 277]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[760 277]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[760 277]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[760 277]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[760 277]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[760 277]
ball_3D
[0 0 0 1]
ball_cam1
[0 0]
ball_cam2
[7

ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760

ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760

ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760

ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760

ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
ball_cam1
[583 299]
ball_cam2
[760 277]
ball_3D
[[0]
 [0]
 [0]
 [0]]
